// ============================================================
// BDOC PHASE 2 MODULE: kitsune-ai.js
// Kitsune AI Copilot — BRIEFS dictionary + sendQ() command processor
// Extracted from js/modules/layers-air.js lines 443-577 (Turn 10, 2026-04-22)
// (Originally pulled into layers-air.js by Turn 8b range overshoot — relocated here)
// Depends on (resolved lazily at call time):
//   esc, msg, Health, Cache, layers, togLy, genPDF, History, Replay, Anomaly,
//   activeFilter, CFG, V, allAC, milAC, cableEnts, sanctionEnts, embassyEnts,
//   powerplantEnts, oilgasEnts, formatTrillion, _econData, US_POP, US_TAXPAYERS,
//   internetHealthData, landingEnts, VegIntel
//   sendQ() is referenced from inline onclick/onkeydown — must be a function declaration
//   so it lands on window via classic-script global object binding.
// (c) 2026 Kitsune Global Solutions LLC
// ============================================================
// ═══════════════════════════════════════════
// SECTION 11: AI COPILOT (v7.0)
// ═══════════════════════════════════════════
const BRIEFS={
iran:()=>`<b>IRAN CRISIS \u2014 SITUATION REPORT</b><br><br><b>DIPLOMATIC:</b> Third round Geneva talks concluded 26 FEB \u2014 "significant progress" claimed but no breakthrough. Vienna technical talks next week. US demands: destroy Fordow/Natanz/Isfahan, surrender enriched uranium. Iran rejects zero enrichment.<br><br><b>MILITARY POSTURE:</b> Largest US air/naval buildup since 2003. ~50,000 troops across CENTCOM AO. USS Gerald R. Ford + USS Abraham Lincoln CSGs deployed. F-35 engaged Shahed drone approaching Lincoln. Senior adviser: "90% chance kinetic action in weeks."<br><br><b>MARITIME:</b> IRGC attempted seizure of US-flagged tanker. Iran seized 2 tankers near Farsi Island. Hormuz temporarily closed during live-fire drill. Khamenei threatened to sink US warships.<br><br><b>ASSESSMENT:</b> No coalition \u2014 only Israel aligned. Iran has ballistic missiles targeting all US bases, proxy networks, ability to close Hormuz (20% global oil). Strike = oil spike + multi-theater escalation.`,
'force tracker':()=>`<b>FORCE TRACKER \u2014 STATUS</b><br><br>Scanning ${CFG.regions.length} regions via OpenSky Network + ADS-B Exchange for military/VIP transponders.<br><br>\u2022 <b>Primary Source:</b> OpenSky Network (opensky-network.org)<br>\u2022 <b>Fallback Source:</b> ADS-B Exchange (api.adsb.lol)<br>\u2022 <b>Callsign Match:</b> ${CFG.milPrefixes.length}+ known military prefixes<br>\u2022 <b>VIP Detection:</b> SAM, AF1, AF2, EXEC, SPAR<br><br><b>Current scan:</b> ${milAC.length} mil/VIP aircraft<br><b>Regions:</b> ${CFG.regions.map(r=>r.name).join(', ')}<br><br><b>What goes dark during crisis = the real signal.</b>`,
ukraine:()=>`<b>UKRAINE SITREP \u2014 EUCOM THEATER</b><br><br><b>GROUND WAR:</b> Russian forces pressing along the entire Donbas line of contact, prioritizing Pokrovsk, Chasiv Yar, and the Zaporizhzhia axis. Ukraine conducting elastic defense with limited counterattacks. Estimated 1,000+ km active front line. Both sides suffering 500-1,000+ casualties/day. Russia committing North Korean troops (est. 10,000-12,000 deployed) alongside Wagner successor units and mobilized infantry.<br><br><b>AIR DOMAIN:</b> Russia launches nightly Shahed-136/Geran-2 drone swarms (50-100 per wave) combined with cruise missiles (Kh-101, Kalibr, Iskander). Ukraine\u2019s air defense (Patriot, NASAMS, IRIS-T, Gepard) intercepts 80-90% but stocks are finite. F-16s now operational with Ukrainian pilots \u2014 limited numbers but significant for BVR engagement and morale.<br><br><b>NATO ISR OVERHEAD:</b><br>\u2022 <b>FORTE11/12</b> (RQ-4B Global Hawk) \u2014 high-altitude SIGINT/IMINT over Black Sea. 30+ hour loiter.<br>\u2022 <b>JAKE11/12</b> (RC-135W Rivet Joint) \u2014 SIGINT collection along Belarus/Russia borders<br>\u2022 <b>NATO01/MAGIC</b> (E-3A AWACS) \u2014 airborne early warning orbits over Poland/Romania<br>\u2022 <b>LAGR/ESSO</b> (KC-135/A330 MRTT) \u2014 tanker orbits supporting CAP and ISR. Surge = increased tempo.<br>\u2022 <b>HOMER/BART</b> (P-8A Poseidon) \u2014 maritime patrol over Black Sea, tracking Russian naval movements<br><br><b>KEY INDICATORS:</b> FORTE flight hours increasing = heightened surveillance before offensive. AWACS orbit shifts = threat axis change. Tanker surge = air campaign tempo increase. Loss of ADS-B signals over Ukraine = GPS jamming/spoofing (Russia operates Pole-21 and Tirada-2 systems).<br><br><b>NUCLEAR RISK:</b> Zaporizhzhia Nuclear Power Plant (6 reactors, largest in Europe) remains under Russian occupation. IAEA monitoring team on-site. Any shelling near cooling infrastructure risks radiological incident. Russia has made veiled nuclear threats; tactical nuclear weapons moved to Belarus.`,
china:()=>`<b>INDOPACOM \u2014 TAIWAN STRAIT / SOUTH CHINA SEA BRIEF</b><br><br><b>TAIWAN STRAIT:</b> PLA conducts near-daily incursions across the Taiwan Strait median line \u2014 PLAAF J-16, Su-30MKK fighters and H-6K bombers averaging 30-50 sorties/month into Taiwan\u2019s ADIZ. PLA Navy Type 052D destroyers and Type 055 cruisers transit the Strait regularly. China\u2019s Eastern Theater Command (responsible for Taiwan contingency) has conducted multiple large-scale joint exercises simulating blockade and amphibious assault. US responds with Freedom of Navigation transits (Arleigh Burke DDGs) and occasional carrier strike group presence.<br><br><b>SEMICONDUCTOR RISK:</b> TSMC (Hsinchu, Taiwan) produces 90% of the world\u2019s most advanced chips (<7nm). A blockade or invasion disrupts the entire global electronics supply chain \u2014 estimated $1-2 trillion economic impact in year one. This is the single most consequential economic chokepoint on Earth.<br><br><b>SOUTH CHINA SEA:</b><br>\u2022 <b>Second Thomas Shoal</b> \u2014 Philippine Marines garrison the grounded BRP Sierra Madre. China Coast Guard (CCG) blocks resupply missions with water cannons and military-grade lasers. Multiple collision incidents with Philippine vessels.<br>\u2022 <b>Spratly Islands</b> \u2014 3 major Chinese artificial islands (Mischief Reef, Fiery Cross, Subi Reef) fully militarized with 3,000m runways, SAM batteries, anti-ship missiles, radar arrays, and underground storage.<br>\u2022 <b>Scarborough Shoal</b> \u2014 Seized from Philippines in 2012. CCG maintains permanent presence. Within fighter range of Clark Air Base.<br>\u2022 <b>Chinese Maritime Militia</b> \u2014 Hundreds of fishing vessels operating as paramilitary force, coordinated by PLA Southern Theater Command.<br><br><b>FORCE POSTURE:</b><br>\u2022 <b>US:</b> 7th Fleet (Yokosuka), III MEF (Okinawa), USAF 5th AF (Misawa/Kadena), 2 carrier strike groups rotational. ~80,000 personnel in INDOPACOM forward positions.<br>\u2022 <b>China:</b> 2 operational carriers (Liaoning, Shandong), Type 003 Fujian in sea trials. World\u2019s largest navy by hull count (370+ vessels). DF-21D/DF-26 "carrier killer" ASBMs. DF-17 hypersonic glide vehicle.<br>\u2022 <b>Allies:</b> Japan (JMSDF, largest non-US navy in Pacific), Australia (AUKUS SSN program), Philippines (Enhanced Defense Cooperation Agreement \u2014 4 new EDCA bases).<br><br><b>WATCH:</b> PLA amphibious ship concentrations at Fujian ports, PLAAF surge sorties, civilian shipping pattern changes (ships avoiding strait = insider knowledge), undersea cable cuts near Taiwan, GPS jamming/spoofing over strait.`,
earthquake:()=>`<b>SEISMIC STATUS \u2014 USGS REAL-TIME FEED</b><br><br><b>SOURCE:</b> United States Geological Survey (earthquake.usgs.gov) \u2014 GeoJSON feed, M2.5+ events, last 24 hours. Refreshes every 5 minutes.<br><br><b>COLOR CODING:</b><br>\u2022 <span style="color:#ff0000">\u25CF RED</span> \u2014 M6.0+ (destructive, potential tsunami)<br>\u2022 <span style="color:#E8B339">\u25CF ORANGE</span> \u2014 M5.0-5.9 (moderate damage likely)<br>\u2022 <span style="color:#E8B339">\u25CF YELLOW</span> \u2014 M4.0-4.9 (widely felt, minor damage)<br>\u2022 <span style="color:#88ff00">\u25CF GREEN</span> \u2014 M2.5-3.9 (felt locally, rarely damaging)<br><br><b>MILITARY/NUCLEAR CROSS-CORRELATION:</b> BDOC monitors ${CFG.milSites.length} military installations and nuclear facilities worldwide. Any M4.0+ earthquake within 100km of a monitored site triggers an automatic anomaly alert. This detects potential infrastructure damage to nuclear power plants, weapons storage facilities, missile silos, and command bunkers.<br><br><b>WHY IT MATTERS:</b> The 2011 Fukushima disaster (M9.0 + tsunami) demonstrated how seismic events can cascade into nuclear emergencies. BDOC provides early cross-domain awareness that single-source seismic monitors miss.<br><br><b>INTELLIGENCE VALUE:</b> Underground nuclear tests produce distinctive seismic signatures (P-wave dominant, shallow depth, known test site location). North Korea\u2019s 6 tests at Punggye-ri all registered as M4.3-6.3 earthquakes. BDOC flags any unusual seismic activity near known test sites.`,
fire:()=>`<b>WILDFIRE \u2014 NASA FIRMS ACTIVE FIRE DATA</b><br><br><b>SOURCE:</b> NASA Fire Information for Resource Management System (FIRMS). Uses the VIIRS instrument aboard Suomi NPP satellite \u2014 375m resolution thermal detection, near-real-time (3-hour latency from overpass).<br><br><b>DETECTION METHOD:</b> VIIRS scans the Earth\u2019s surface in mid-infrared (4\u03BCm) and thermal infrared (11\u03BCm) bands. Active fires produce a distinctive thermal signature that VIIRS distinguishes from hot surfaces, industrial heat, and sun glint. Each detection point represents a ~375m\u00B2 pixel where fire was confirmed.<br><br><b>DATA FIELDS:</b><br>\u2022 <b>Brightness (K)</b> \u2014 Fire radiative temperature in Kelvin. Higher = more intense. >400K is a major fire.<br>\u2022 <b>FRP (MW)</b> \u2014 Fire Radiative Power in megawatts. Measures energy output. >100MW = large, dangerous fire.<br>\u2022 <b>Confidence</b> \u2014 Detection confidence (low/nominal/high). BDOC shows nominal+ only.<br><br><b>COVERAGE:</b> Continental US. Refreshes every 15 minutes from FIRMS API.<br><br><b>CROSS-DOMAIN INTELLIGENCE:</b><br>\u2022 Fires near military installations \u2192 potential base evacuations, training disruptions<br>\u2022 Fires near nuclear facilities \u2192 evacuation zone overlap, smoke plume hazards<br>\u2022 Fires near power infrastructure \u2192 grid outage cascades (see Power Outage layer)<br>\u2022 Coordinated ignition patterns \u2192 potential arson/sabotage indicator<br>\u2022 Conflict zone fires \u2192 scorched earth tactics, infrastructure destruction<br><br><b>HISTORICAL CONTEXT:</b> The 2023 Maui wildfire killed 100+ people with <2hr warning. FIRMS data showed the ignition within one satellite pass. Real-time fire monitoring saves lives.`,
satellite:()=>`<b>SATELLITE TRACKING \u2014 SPACE DOMAIN AWARENESS</b><br><br><b>SOURCE:</b> CelesTrak (celestrak.org) \u2014 aggregates NORAD Two-Line Element (TLE) sets from the 18th Space Defense Squadron, Vandenberg SFB. Updated multiple times daily.<br><br><b>HOW IT WORKS:</b> TLE data contains 6 Keplerian orbital elements per satellite. BDOC uses SGP4 propagation to calculate real-time position from the last TLE epoch. Accuracy degrades ~1-2km/day from epoch — sufficient for awareness, not targeting.<br><br><b>WHAT\u2019S TRACKED:</b><br>\u2022 <b>ISS + crewed vehicles</b> \u2014 Zarya, Dragon, Starliner, Soyuz, Shenzhou<br>\u2022 <b>Bright/visual satellites</b> \u2014 Starlink trains, Iridium, large debris<br>\u2022 <span style="color:#DA3633"><b>MILITARY ASSESSED (RED)</b></span> \u2014 USA-designated NRO payloads, NOSS ocean surveillance pairs, LACROSSE/Onyx radar imaging, TRUMPET/MENTOR SIGINT, GPS III navigation, SBIRS missile warning, WGS/AEHF military comms<br><br><b>MILITARY SATELLITE TYPES:</b><br>\u2022 <b>SIGINT (Signals Intelligence)</b> \u2014 TRUMPET, MENTOR, INTRUDER \u2014 intercept communications and radar emissions from GEO orbit<br>\u2022 <b>IMINT (Imagery Intelligence)</b> \u2014 KH-11 (USA-224, USA-314 etc.) \u2014 electro-optical, ~10cm resolution estimated<br>\u2022 <b>SAR (Radar Imaging)</b> \u2014 LACROSSE/Onyx \u2014 all-weather, day/night ground imaging<br>\u2022 <b>NOSS (Ocean Surveillance)</b> \u2014 Fly in pairs/triplets, triangulate ship radar emissions to track naval movements globally<br>\u2022 <b>SBIRS (Missile Warning)</b> \u2014 GEO + HEO constellation, detects ICBM/IRBM launches within seconds via infrared plume detection<br>\u2022 <b>GPS III</b> \u2014 Military M-code provides jam-resistant, encrypted positioning for precision munitions<br><br><b>INTELLIGENCE VALUE:</b> Satellite pass timing reveals collection windows. If a KH-11 is overhead during a military exercise, imagery was likely collected. NOSS pairs over a naval fleet = real-time ship tracking. Understanding orbital mechanics = understanding who can see what, when.<br><br><b>Currently tracking:</b> ${satEnts.length} satellites on globe`,
health:()=>`<b>SYSTEM HEALTH \u2014 FEED MONITORING DASHBOARD</b><br><br>Press <b>Ctrl+Shift+H</b> to open the full health dashboard overlay.<br><br><b>WHAT\u2019S MONITORED:</b> Every external data feed is tracked by the Health subsystem. Each API call through <code>safeFetch()</code> records response time, HTTP status, error count, and cache behavior.<br><br><b>STATUS LEVELS:</b><br>\u2022 <span style="color:#3FB950">\u25CF HEALTHY</span> \u2014 Feed responding normally, data fresh, <2s response time<br>\u2022 <span style="color:#E8B339">\u25CF DEGRADED</span> \u2014 Slow responses (>5s), partial data, or using cached fallback<br>\u2022 <span style="color:#ff4400">\u25CF DOWN</span> \u2014 Feed unreachable. BDOC serves last-known cached data if available.<br><br><b>DASHBOARD METRICS:</b><br>\u2022 <b>Response Time</b> \u2014 Average API latency per feed (ms)<br>\u2022 <b>Error Count</b> \u2014 Cumulative failures since boot<br>\u2022 <b>Cache Hit Rate</b> \u2014 % of requests served from local cache vs live API<br>\u2022 <b>Last Success</b> \u2014 Timestamp of last successful data fetch<br>\u2022 <b>System Uptime</b> \u2014 Time since BDOC boot<br><br><b>RESILIENCE:</b> BDOC is designed to degrade gracefully. If a feed goes down, cached data continues rendering. Multiple feeds can fail without affecting the rest. The anomaly detection system flags when feeds go dark unexpectedly \u2014 a feed outage can itself be an intelligence indicator (e.g., OpenSky going dark over a conflict zone may indicate GPS jamming).`,
outages:()=>`<b>POWER OUTAGE MONITORING</b><br><br>Tracking <b>28 major US electric utilities</b> including:<br><br>\u2022 <b>KUBRA Storm Center</b> utilities: National Grid, Georgia Power, Duke Energy, Dominion, AEP, ComEd, Eversource, Entergy, DTE, Alabama Power, Mississippi Power<br>\u2022 <b>Custom platforms</b>: FPL, SoCal Edison, PG&E, ConEdison, CenterPoint, Xcel, Ameren, PECO, PSE&G, PPL Electric<br>\u2022 <b>Aggregator</b>: PowerOutage.us / USOutage.com (nationwide)<br><br><b>Current entities:</b> ${outageEnts.length} on map<br><br><b>Note:</b> Utility outage APIs (KUBRA Storm Center) use CORS restrictions that block direct browser access. With a server-side proxy (Cloudflare Worker), BDOC can show real-time county-level outage counts from all 28 utilities.<br><br>Each marker links to the utility\u2019s live outage map.`,
service:()=>`<b>SERVICE STATUS MONITOR</b><br><br>Real-time status checks via <b>Atlassian Statuspage API v2</b>:<br><br>${downEnts.length} services monitored including Cloudflare, GitHub, Discord, Meta, Fastly, Datadog, Twilio, Zoom, Reddit, Dropbox, Heroku, DigitalOcean, Vercel, Netlify.<br><br><b>Status Levels:</b><br>\u2022 \u2705 <span style="color:#3FB950">OPERATIONAL</span> \u2014 All systems normal<br>\u2022 \u26A0\uFE0F <span style="color:#E8B339">DEGRADED</span> \u2014 Performance issues detected<br>\u2022 \uD83D\uDD34 <span style="color:#ff4400">MAJOR OUTAGE</span> \u2014 Service significantly impaired<br>\u2022 \uD83D\uDD34 <span style="color:#ff0000">CRITICAL</span> \u2014 Service down<br><br>All data is <b>LIVE</b> \u2014 fetched directly from each service\u2019s official status page API. No simulation.`,
celltowers:()=>`<b>CELL TOWER INFRASTRUCTURE</b><br><br>Maps cellular communication towers from <b>OpenStreetMap</b> via Overpass API.<br><br>Color-coded by carrier:<br>\u2022 <span style="color:#0057b8">AT&T (Blue)</span><br>\u2022 <span style="color:#cd040b">Verizon (Red)</span><br>\u2022 <span style="color:#e20074">T-Mobile (Magenta)</span><br>\u2022 <span style="color:#888">Other / Unknown (Gray)</span><br><br>Technology tags shown: 5G NR, 4G LTE, 3G UMTS, 2G GSM<br><br><b>Currently showing:</b> ${cellTowerEnts.length} towers in view<br><br>Zoom into a city (max 5\u00B0 span) and toggle ON to load. Data density depends on OSM community mapping.<br><br><i>Similar to: CellMapper.net, CellularFinder.com, CellTowerMaps.com</i>`,
radio:()=>`<b>RADIO SIGINT \u2014 COMPREHENSIVE</b><br><br>Three data categories loaded:<br><br>\uD83C\uDF0A <b style="color:#4499ff">NOAA Weather Radio (NWR):</b> 25 transmitter stations with frequencies and power output. 24/7 automated NWS weather broadcasts + EAS alerts.<br><br>\uD83D\uDCFB <b style="color:#aa44ff">AM/FM Broadcast Stations:</b> 30 major licensed stations including clear-channel 50kW powerhouses (WSB, WOR, WABC, KFI, WBBM, KDKA, WBZ, etc.) with real call signs and frequencies.<br><br>\uD83D\uDE94 <b style="color:#DA3633">Police/Fire/EMS Scanners:</b> 25 major city scanner feeds via Broadcastify. Live dispatch audio from NYPD, LAPD, Chicago PD, Houston PD, Atlanta PD, and 20 more.<br><br><b>Total:</b> ${radioEnts.length} sources on map`,
deflock:()=>`<b>DeFlock SURVEILLANCE LAYER</b><br><br>Maps surveillance infrastructure from <b>DeFlock.org</b> / OpenStreetMap data:<br><br>\u2022 <b style="color:#DA3633">ALPRs</b> \u2014 Automated License Plate Readers (Flock Safety, Vigilant, etc.)<br>\u2022 <b style="color:#E8B339">Gunshot Detectors</b> \u2014 ShotSpotter/SoundThinking acoustic sensors<br>\u2022 <b style="color:#4A9EFF">AI Cameras</b> \u2014 Computer vision surveillance cameras<br><br>Data sourced from OpenStreetMap via Overpass API. Coverage depends on community mapping efforts \u2014 densest in US/EU cities.<br><br><b>Currently showing:</b> ${deflockEnts.length} surveillance devices in view<br><br>Zoom into a city and toggle the layer ON to load devices in your view area. Max query span: 30\u00B0.<br><br><i>Learn more: <span style="color:var(--bl)">deflock.org</span></i>`,
chokepoints:()=>`<b>STRATEGIC CHOKEPOINTS</b><br><br>6 global maritime chokepoints with threat analysis and fly-to navigation:<br><br>\u2022 <b style="color:#DA3633">Strait of Hormuz</b> \u2014 20% of global oil. Iran can mine/blockade. 5/5 threat.<br>\u2022 <b style="color:#E8B339">Taiwan Strait</b> \u2014 90% advanced semiconductors. PLA naval pressure. 4/5 threat.<br>\u2022 <b style="color:#E8B339">Strait of Malacca</b> \u2014 25% of global trade. Piracy corridor. 3/5 threat.<br>\u2022 <b style="color:#E8B339">Suez Canal</b> \u2014 12% global trade. Houthi anti-ship attacks. 3/5 threat.<br>\u2022 <b style="color:#E8B339">Panama Canal</b> \u2014 5% global trade. Drought restricting transits. 2/5 threat.<br>\u2022 <b style="color:#E8B339">GIUK Gap</b> \u2014 NATO submarine detection zone. Russian SSN activity. 3/5 threat.<br><br>Toggle <b>Chokepoints</b> in the left panel to view on globe.`,
bases:()=>`<b>MILITARY INSTALLATIONS</b><br><br>Tracking <b>146 military bases</b> worldwide (US/RU/CN/Allied):<br><br>\u2022 <span style="color:#3FB950">GREEN</span> \u2014 US/Allied bases<br>\u2022 <span style="color:#DA3633">RED</span> \u2014 Adversary bases (Russia, China, Iran, DPRK)<br><br>Includes ICBM/bomber bases, naval stations, air bases, and forward operating locations. Toggle <b>Military Bases</b> in the left panel.`,
nuclear:()=>`<b>NUCLEAR TEST SITES</b><br><br>Tracking <b>12 nuclear test sites</b> worldwide with contamination rings:<br><br>\u2022 Nevada Test Site (USA) \u2014 928 tests<br>\u2022 Semipalatinsk (Kazakhstan) \u2014 456 tests<br>\u2022 Novaya Zemlya (Russia) \u2014 Tsar Bomba site<br>\u2022 Lop Nur (China) \u2014 45 tests<br>\u2022 Punggye-ri (DPRK) \u2014 6 tests (2006-2017)<br>\u2022 Reggane/In Ekker (Algeria/France) \u2014 17 tests<br>\u2022 Mururoa/Fangataufa (French Polynesia) \u2014 193 tests<br>\u2022 Maralinga/Emu Field (Australia/UK) \u2014 12 tests<br>\u2022 Christmas/Malden Islands (UK) \u2014 atmospheric tests<br>\u2022 Pokhran (India) \u2014 6 tests<br>\u2022 Ras Koh Hills (Pakistan) \u2014 6 tests<br><br>Contamination rings show estimated fallout zones. Toggle <b>Nuclear Test Sites</b> in the left panel.`,
squawk:()=>`<b>EMERGENCY SQUAWK MONITORING</b><br><br>Monitoring all aircraft transponder codes for emergency squawks:<br><br>\u2022 <b style="color:#ff0000">7700</b> \u2014 GENERAL EMERGENCY (engine failure, medical, structural)<br>\u2022 <b style="color:#E8B339">7600</b> \u2014 RADIO FAILURE (lost comms, NORDO)<br>\u2022 <b style="color:#DA3633">7500</b> \u2014 HIJACK (confirmed or suspected)<br>\u2022 <b style="color:#4A9EFF">7400</b> \u2014 UAS LOST LINK (drone lost control signal)<br><br>BDOC scans all tracked aircraft transponders in real-time. Any emergency squawk triggers an immediate alert in the event log and Kitsune AI chat.<br><br>Currently scanning ${typeof milAC!=='undefined'?milAC.length:0} military + ${typeof allAC!=='undefined'&&typeof milAC!=='undefined'?(allAC.length-milAC.length):0} civilian aircraft.`,
internet:()=>`<b>INTERNET HEALTH \u2014 CLOUDFLARE RADAR</b><br><br>Monitors global internet health via Cloudflare Radar API.<br><br>\u2022 <b>BGP Route Leaks/Hijacks</b> \u2014 detects unauthorized route announcements<br>\u2022 <b>Traffic Anomalies</b> \u2014 sudden drops indicating outages or censorship<br>\u2022 <b>DDoS Attack Volume</b> \u2014 aggregate attack traffic metrics<br><br>Toggle <b>Internet Health (CF Radar)</b> in the left panel to view. Data refreshes every 15 minutes.`,
help:()=>`<b>KGS BDOC v7.0 \u2014 COMMANDS</b><br><br>\u2022 <b>iran</b> / <b>centcom</b> \u2014 Iran crisis brief<br>\u2022 <b>ukraine</b> / <b>eucom</b> \u2014 Ukraine sitrep<br>\u2022 <b>china</b> / <b>indopacom</b> \u2014 Taiwan/SCS brief<br>\u2022 <b>force tracker</b> \u2014 Military aircraft status<br>\u2022 <b>satellite</b> \u2014 Satellite tracking status<br>\u2022 <b>earthquake</b> \u2014 Seismic activity<br>\u2022 <b>fire</b> \u2014 Active fire detections<br>\u2022 <b>chokepoints</b> \u2014 Strategic chokepoint analysis<br>\u2022 <b>internet</b> \u2014 Cloudflare Radar health<br>\u2022 <b>cables</b> \u2014 Submarine cable intel<br>\u2022 <b>anomalies</b> \u2014 Recent anomaly alerts<br>\u2022 <b>export brief</b> \u2014 Generate PDF intel brief<br>\u2022 <b>history</b> / <b>replay</b> \u2014 Historical data<br>\u2022 <b>health</b> \u2014 System health status<br>\u2022 <b>status</b> / <b>sitrep</b> \u2014 Full system overview<br>\u2022 <b>bases</b> \u2014 Military installations map<br>\u2022 <b>nuclear</b> \u2014 Nuclear test sites<br>\u2022 <b>nuke [kt or warhead]</b> \u2014 detonation simulator, e.g. <b>nuke w87</b> or <b>detonate 250 surface</b> (modern: W76-2/B61-12/W76-1/DF-41/W87/W88/Yars)<br>\u2022 <b>squawk</b> \u2014 Emergency squawk monitoring<br>\u2022 <b>deflock</b> / <b>surveillance</b> \u2014 Surveillance camera mapping<br>\u2022 <b>outages</b> / <b>power</b> \u2014 Power outage monitoring (28 utilities)<br>\u2022 <b>service</b> / <b>downdetector</b> \u2014 Service status (15 platforms, LIVE)<br>\u2022 <b>celltowers</b> / <b>cellular</b> \u2014 Cell tower infrastructure (OSM)<br>\u2022 <b>radio</b> / <b>scanner</b> \u2014 NOAA + AM/FM + Police scanners<br>\u2022 <b>debt</b> / <b>economy</b> \u2014 US national debt + economic intel<br>\u2022 <b>sanctions</b> / <b>ofac</b> \u2014 OFAC/UN/EU sanctioned entities<br>\u2022 <b>alliances</b> / <b>nato</b> \u2014 NATO/CSTO/BRICS+/Five Eyes/AUKUS/Quad<br>\u2022 <b>power plants</b> \u2014 Global power generation facilities<br>\u2022 <b>oil</b> / <b>gas</b> / <b>lng</b> \u2014 Energy infrastructure &amp; chokepoints<br>\u2022 <b>embassy</b> \u2014 US &amp; foreign diplomatic missions<br>\u2022 <b>vegetation</b> / <b>veg scan</b> \u2014 Terrain/vegetation intelligence (NDVI + species)<br>\u2022 <b>ip [address]</b> / <b>my ip</b> \u2014 IP geolocation + VPN/TOR/proxy detection<br>\u2022 <b>help</b> \u2014 This command list`
};
function sendQ(){
  const inp=document.getElementById('aiIn');const q=inp.value.trim().toLowerCase();
  if(!q)return;
  msg('us',esc(q));inp.value='';
  let matched=false;
  // ── P91: LIVE SITREP ENGINE — natural-language theater questions get LIVE answers,
  // not static briefs. Triggers on "sitrep <theater>", or any question combining a
  // theater name with intel-question words (what/happened/hit/attack/casualt/killed/
  // strikes/bases/24|today|latest|now/who). Static BRIEFS remain the fallback for a
  // bare theater name (e.g. just "iran" still gives the background brief).
  try{
    const thKeys=Object.keys(window.SITREP_THEATERS||{});
    const TH_FALLBACK=['iran','ukraine','gaza','israel','lebanon','yemen','sudan','myanmar','sahel','taiwan'];
    const thHit=(thKeys.length?thKeys:TH_FALLBACK).find(k=>q.includes(k));
    const intent=/sitrep|what.{0,20}(happen|going on)|attack|strike|hit|casualt|killed|injured|wounded|bases?|latest|today|last 24|past 24|update|right now|live/i.test(q);
    if(thHit&&(intent||q.startsWith('sitrep'))){
      msg('sy','<b>⚡ GENERATING LIVE SITREP — '+thHit.toUpperCase()+'</b><br><span style="font-size:9px;color:#8b949e">Pulling 24h global media + geocoded kinetic events…</span>');
      const run=()=>window.generateSitrep(thHit).catch(e=>{console.warn('[SITREP]',e);msg('sy','<b>SITREP ERROR</b><br>'+esc(String(e&&e.message||e)))});
      if(window.generateSitrep)run();
      else if(window.BDOC&&BDOC.LazyLoader)BDOC.LazyLoader.load('sitrep-engine').then(run).catch(e=>msg('sy','<b>SITREP module failed to load.</b> '+esc(String(e&&e.message||e))));
      return;
    }
    if(q==='sitrep'||q==='sitreps'){
      msg('sy','<b>LIVE SITREP</b><br><br>Ask me about a theater, e.g.:<br>&bull; <b>sitrep iran</b> — or just "what happened in iran in the last 24 hours?"<br>&bull; <b>sitrep ukraine</b>, <b>sitrep gaza</b>, <b>sitrep yemen</b>, <b>sitrep sudan</b>, <b>sitrep myanmar</b>, <b>sitrep sahel</b>, <b>sitrep taiwan</b><br><br>I\'ll pull the last 24h of global reporting and extract: who attacked whom, installations hit, and casualty claims — with sources.');
      return;
    }
  }catch(_){}
  const aliases={centcom:'iran',eucom:'ukraine',indopacom:'china',satellites:'satellite',sat:'satellite',ships:'vessels',maritime:'vessels',ais:'vessels',surveillance:'deflock',alpr:'deflock',flock:'deflock',cameras:'deflock',power:'outages',blackout:'outages',grid:'outages','power outage':'outages',downdetector:'service',services:'service','status check':'service','cell tower':'celltowers',cellular:'celltowers',towers:'celltowers','5g':'celltowers',lte:'celltowers',scanner:'radio',scanners:'radio',police:'radio',noaa:'radio','weather radio':'radio',broadcastify:'radio',economy:'debt',fiscal:'debt','national debt':'debt','debt clock':'debt',treasury:'debt',ofac:'sanctions',sdn:'sanctions',watchlist:'sanctions',nato:'alliances',brics:'alliances',csto:'alliances','five eyes':'alliances',aukus:'alliances',lng:'oil',refinery:'oil',pipeline:'oil',energy:'oil',consulate:'embassy',diplomatic:'embassy','power plant':'powerplants',powerplant:'powerplants',ndvi:'vegetation',flora:'vegetation',canopy:'vegetation',jungle:'vegetation',terrain:'vegetation','veg scan':'vegetation','plant id':'vegetation',biome:'vegetation',geolocate:'ip lookup','ip trace':'trace ip','ip intel':'ip lookup',whois:'ip lookup'};
  const qNorm=aliases[q]||q;
  for(const[key,val]of Object.entries(BRIEFS)){
    if(qNorm===key||qNorm.startsWith(key+' ')){const brief=typeof val==='function'?val():val;msg('sy',brief);matched=true;break}
  }
  if(matched)return;
  if(q.includes('status')||q.includes('sitrep')){
    const h=Health.sysHealth(),fc=Object.values(Health.feeds).filter(f=>f.status==='healthy').length,tf=Object.keys(Health.feeds).length;
    msg('sy',`<b>SYSTEM STATUS \u2014 BDOC v${CFG.version}</b><br><br>Health: <b>${h.toUpperCase()}</b><br>Feeds: ${fc}/${tf} operational<br>Aircraft: ${allAC.length} tracked (${milAC.length} military)<br>Earthquakes: ${document.getElementById('eqV').textContent}<br>Fires: ${document.getElementById('fireV').textContent}<br>Satellites: ${document.getElementById('satV').textContent}<br>Conflicts: ${document.getElementById('conV').textContent}<br>Anomalies: ${Anomaly.alerts.length} detected<br>Cache: ${Cache.stats.hits} hits / ${Cache.stats.misses} misses<br>Uptime: ${Health.tAgo(Health.bootTime)}<br>Filter: ${activeFilter||'CLEAN'}`);
  }else if(q.includes('cable')||q.includes('submarine')){
    msg('sy',`<b>SUBMARINE CABLES</b><br><br>TeleGeography data loaded. ${cableEnts.length} cable segments rendered.<br><br>Submarine cables carry 97% of intercontinental data. Damage = massive comms disruption. Watch for: anchor drags, seismic events near cable routes, state-sponsored sabotage.`);
  }else if(q.includes('anomal')){
    if(Anomaly.alerts.length===0){msg('sy','<b>ANOMALY LOG</b><br><br>No anomalies detected. System is monitoring for:<br>\u2022 Military aircraft count surges (>150% of baseline)<br>\u2022 M4.0+ earthquakes within 100km of military/nuclear facilities<br><br>Anomaly detection runs continuously.')}
    else{let html='<b>ANOMALY LOG \u2014 Last '+Math.min(Anomaly.alerts.length,10)+' alerts</b><br><br>';Anomaly.alerts.slice(-10).forEach(a=>{html+=`<span style="color:var(--t3)">${a.ts.slice(11,19)}Z</span> ${a.message}<br>`});msg('al',html)}
  }else if(q==='clear nuke'||q==='clear nukes'||q==='nuke clear'||q==='clear detonation'){
    if(typeof clearNukeSim==='function'){clearNukeSim();msg('sy','<b>Detonation effects cleared.</b>');}
    else msg('sy','No active detonation to clear.');
  }else if(q==='nuke'||q==='detonate'||q.startsWith('nuke ')||q.startsWith('detonate ')){
    // "nuke w87" / "detonate 250 surface" — yield in kt OR a modern warhead name.
    // Detonates at the current camera center. Right-click → "Nuclear Detonation" targets a precise point.
    const arg=q.replace(/^(nuke|detonate)\s*/,'').trim();
    const toks=arg.split(/\s+/).filter(Boolean);
    const surface=toks.some(t=>t==='surface'||t==='ground'||t==='s');
    const yieldTok=toks.find(t=>t!=='surface'&&t!=='ground'&&t!=='s')||'w87';
    const cam=V?Cesium.Cartographic.fromCartesian(V.camera.positionWC):null;
    const clat=cam?Cesium.Math.toDegrees(cam.latitude):0;
    const clon=cam?Cesium.Math.toDegrees(cam.longitude):0;
    af('#ff2200',`Computing ${surface?'surface':'air'}burst at view center…`);
    BDOC.LazyLoader.load('nuke-sim').then(()=>window.detonateNuke(clon,clat,yieldTok,{surface})).catch(e=>{console.warn('[lazy nuke-sim]',e);msg('sy','<span style="color:var(--rd)">Failed to load detonation module.</span>')});
  }else if(q.startsWith('save as ')||q.startsWith('save workspace ')){
    // Workspace save: "save as NAME" or "save workspace NAME"
    const name=(q.startsWith('save as ')?q.slice(8):q.slice(15)).trim()||'default';
    if(typeof saveWorkspace==='function'){
      const ws=saveWorkspace(name);
      if(ws)msg('sy',`<b>WORKSPACE SAVED: "${esc(name)}"</b><br><br>Camera position + ${(ws.layers||[]).length} active layers captured.<br>Type <b>load ${esc(name)}</b> to restore.`);
      else msg('sy','<span style="color:var(--rd)">Workspace save failed — globe not ready.</span>');
    }else{msg('sy','Workspace module not available.');}
  }else if(q.startsWith('load ')||q.startsWith('load workspace ')){
    // Workspace load: "load NAME" or "load workspace NAME"
    const name=(q.startsWith('load workspace ')?q.slice(15):q.slice(5)).trim();
    if(!name){msg('sy','Usage: <b>load NAME</b>');
    }else if(typeof loadWorkspace==='function'){
      const ok=loadWorkspace(name);
      if(ok)msg('sy',`<b>WORKSPACE LOADED: "${esc(name)}"</b><br><br>Camera and layers restored.`);
      else{const list=typeof listWorkspaces==='function'?listWorkspaces():[];
        msg('sy',`<span style="color:var(--rd)">Workspace "<b>${esc(name)}</b>" not found.</span><br><br>${list.length?'Available: <b>'+list.map(n=>esc(n)).join('</b>, <b>')+'</b>':'No workspaces saved yet. Type <b>save as NAME</b> to create one.'}`);
      }
    }else{msg('sy','Workspace module not available.');}
  }else if(q==='workspaces'||q==='list workspaces'||q==='saved workspaces'){
    const list=typeof listWorkspaces==='function'?listWorkspaces():[];
    if(!list.length){msg('sy','<b>WORKSPACES</b><br><br>No workspaces saved yet.<br><br>Type <b>save as NAME</b> to snapshot camera position + active layers.');}
    else{msg('sy','<b>WORKSPACES</b><br><br>Saved: <b>'+list.map(n=>esc(n)).join('</b>, <b>')+'</b><br><br>Type <b>load NAME</b> to restore any workspace.');}
  }else if(q.includes('export')||q.includes('brief')||q.includes('pdf')){
    genPDF();
  }else if(q.includes('history')||q.includes('replay')){
    const s=History.getSummary();
    if(q.includes('replay')&&History.aircraft.length>=2){Replay.open()}
    else{msg('sy',`<b>HISTORICAL DATA BUFFER</b><br><br>Aircraft snapshots: ${s.acSnaps}<br>Earthquake snapshots: ${s.eqSnaps}<br>Time span: ~${s.spanH}h<br><br>Type <b>replay</b> or press <b>R</b> to open replay timeline.`)}
  }else if(q.includes('chokepoint')||q.includes('choke')){
    msg('sy',(BRIEFS.chokepoints&&BRIEFS.chokepoints())||'Chokepoints module loading...');
  }else if(q.includes('internet')||q.includes('cloudflare')||q.includes('cf radar')){
    msg('sy',(BRIEFS.internet&&BRIEFS.internet())||'Internet health module loading...');
    if(typeof internetHealthData!=='undefined'&&internetHealthData){
      msg('in',`<b>Latest CF Radar data:</b> ${internetHealthData.outages.length} outage annotations. Last checked: ${new Date(internetHealthData.ts).toISOString().slice(11,19)}Z`);
    }
  }else if(q.includes('landing')&&q.includes('cable')){
    msg('sy',`<b>CABLE LANDING POINTS</b><br><br>${typeof landingEnts!=='undefined'?landingEnts.length:0} landing points loaded from TeleGeography.<br><br>Toggle the "Cable Landing Points" layer in the left panel to view.`);
  }else if(q.includes('debt')||q.includes('econom')||q.includes('treasury')||q.includes('fiscal')){
    if(_econData){
      const perCitizen=((_econData.totalDebt/US_POP)).toLocaleString('en-US',{maximumFractionDigits:0});
      const perTaxpayer=((_econData.totalDebt/US_TAXPAYERS)).toLocaleString('en-US',{maximumFractionDigits:0});
      const dailyGrowth=4500000000; // ~$4.5B/day
      msg('sy',`<b>US ECONOMIC INTELLIGENCE \u2014 TREASURY DATA</b><br><br><b>National Debt:</b> $${formatTrillion(_econData.totalDebt)}<br><b>Held by Public:</b> $${formatTrillion(_econData.publicDebt)}<br><b>Intragovernmental:</b> $${formatTrillion(_econData.intragovDebt)}<br><b>Debt Per Citizen:</b> $${perCitizen}<br><b>Debt Per Taxpayer:</b> $${perTaxpayer}<br><b>Daily Growth Rate:</b> ~$${formatTrillion(dailyGrowth)}/day<br><b>As of:</b> ${_econData.date}<br><br><b>STRATEGIC CONTEXT:</b><br>\u2022 National debt directly impacts defense spending capacity<br>\u2022 Rising interest rates increase debt service burden<br>\u2022 Debt-to-GDP ratio is a key indicator of economic stability<br>\u2022 Foreign-held debt (China, Japan) creates geopolitical leverage<br>\u2022 Fiscal pressure may force defense budget adjustments<br><br><span style="color:var(--t3)">Source: US Treasury Fiscal Data API \u2014 api.fiscaldata.treasury.gov</span>`);
    }else{
      if(!layers.econintel){msg('sy','Economic Intel layer is off. Toggle <b>US Economic Intelligence</b> in Auxiliary layers, or type <b>debt</b> again after it loads.')
      ;const el=document.querySelector('[data-layer="econintel"]');if(el){togLy(el)}}
      else{msg('sy','Loading Treasury data... type <b>debt</b> again in a moment.')}
    }
  }else if(q.includes('sanction')||q.includes('ofac')||q.includes('watchlist')||q.includes('sdn')){
    if(!layers.sanctions){const el=document.querySelector('[data-layer="sanctions"]');if(el)togLy(el)}
    const cnt=sanctionEnts.length;
    msg('sy',`<b>SANCTIONS &amp; WATCHLISTS</b><br><br><b>${cnt} sanctioned entities</b> mapped across 6 country programs:<br><br>\u2022 <span style="color:#DA3633">IRAN</span> \u2014 IRGC, nuclear facilities, banks, shipping (OFAC SDN / UNSCR)<br>\u2022 <span style="color:#CC0000">RUSSIA</span> \u2014 Kremlin, Gazprom, Rosneft, Wagner, naval bases (OFAC / EU / G7)<br>\u2022 <span style="color:#880000">NORTH KOREA</span> \u2014 Yongbyon, Punggye-ri, KOMID proliferation network<br>\u2022 <span style="color:#DD4400">CHINA (PRC)</span> \u2014 PLA SSF, Huawei, SMIC, Xinjiang camps (Entity List / OFAC CMC)<br>\u2022 <span style="color:#993300">SYRIA</span> \u2014 Assad regime, SSRC chemical weapons (Caesar Act)<br>\u2022 <span style="color:#AA4400">VENEZUELA</span> \u2014 PDVSA, central bank (EO 13850/13884)<br><br><span style="color:var(--t3)">Sources: OFAC SDN List, UN Security Council Consolidated List, EU Sanctions</span>`);
  }else if((q.includes('alliance')||q.includes('nato')||q.includes('brics')||q.includes('five eyes')||q.includes('aukus')||q.includes('quad'))&&!q.includes('squad')){
    if(!layers.alliances){const el=document.querySelector('[data-layer="alliances"]');if(el)togLy(el)}
    msg('sy',`<b>ALLIANCE MAPS</b><br><br>6 geopolitical alliances mapped:<br><br>\u2022 <span style="color:#0055A4">NATO</span> \u2014 32 members (Finland &amp; Sweden added 2023-2024)<br>\u2022 <span style="color:#CC0000">CSTO</span> \u2014 6 members (Russia-led collective security)<br>\u2022 <span style="color:#FF9500">BRICS+</span> \u2014 11 members (expanded Jan 2024: Egypt, Ethiopia, Iran, UAE, Saudi Arabia, Indonesia)<br>\u2022 <span style="color:#00BFFF">Five Eyes</span> \u2014 US/UK/CA/AU/NZ intelligence sharing<br>\u2022 <span style="color:#7B68EE">AUKUS</span> \u2014 AU/UK/US nuclear submarine + tech pact<br>\u2022 <span style="color:#00CC88">Quad</span> \u2014 US/Japan/India/Australia Indo-Pacific security<br><br>Toggle in the GEOPOLITICAL section of the left panel.`);
  }else if(q.includes('power plant')||q.includes('energy grid')||q.includes('nuclear plant')){
    if(!layers.powerplants){const el=document.querySelector('[data-layer="powerplants"]');if(el)togLy(el)}
    msg('sy',`<b>POWER PLANTS</b><br><br>${powerplantEnts.length} major power generation facilities mapped globally:<br><br>\u2022 <span style="color:#DA3633">Nuclear</span> \u2014 Palo Verde, Kashiwazaki-Kariwa, Zaporizhzhia, Barakah +more<br>\u2022 <span style="color:#555">Coal</span> \u2014 Tuoketuo, Belchatow, Medupi, Kusile +more<br>\u2022 <span style="color:#FF8C00">Natural Gas</span> \u2014 Surgut-2, Jebel Ali, Shoaiba +more<br>\u2022 <span style="color:#4A9EFF">Hydroelectric</span> \u2014 Three Gorges (22.5 GW), Itaipu, Baihetan +more<br>\u2022 <span style="color:#00CC66">Wind</span> \u2014 Gansu, Dogger Bank, Hornsea +more<br>\u2022 <span style="color:#FFD700">Solar</span> \u2014 Bhadla, Benban, Pavagada +more<br><br><span style="color:var(--t3)">Source: WRI Global Power Plant Database</span>`);
  }else if(q.includes('oil')||q.includes('gas')||q.includes('refiner')||q.includes('lng')||q.includes('pipeline')){
    if(!layers.oilgas){const el=document.querySelector('[data-layer="oilgas"]');if(el)togLy(el)}
    msg('sy',`<b>OIL &amp; GAS INFRASTRUCTURE</b><br><br>${oilgasEnts.length} critical energy facilities mapped:<br><br>\u2022 <span style="color:#FF8C00">Refineries</span> \u2014 Jamnagar (1.24M bpd), Port Arthur, Ruwais, SK Ulsan +more<br>\u2022 <span style="color:#00BFFF">LNG Terminals</span> \u2014 Qatargas (77 MTPA), Sabine Pass, Yamal, Bintulu +more<br>\u2022 <span style="color:#CC6600">Pipeline Chokepoints</span> \u2014 Hormuz transit, SUMED, BTC, TurkStream, Druzhba<br>\u2022 <span style="color:#1a1a1a;background:#444;padding:0 3px">Oil Fields</span> \u2014 Ghawar (3.8M bpd), Burgan, Permian Basin +more<br>\u2022 <span style="color:#8B4513">Gas Fields</span> \u2014 South Pars/North Dome (largest in world)<br><br><span style="color:var(--t3)">Sources: EIA, OPEC, IEA, industry reports</span>`);
  }else if(q.includes('embassy')||q.includes('consulate')||q.includes('diplom')){
    if(!layers.embassies){const el=document.querySelector('[data-layer="embassies"]');if(el)togLy(el)}
    msg('sy',`<b>EMBASSIES &amp; DIPLOMATIC MISSIONS</b><br><br>${embassyEnts.length} diplomatic posts mapped:<br><br>\u2022 <span style="color:#4A90D9">US Embassies</span> \u2014 Baghdad (largest), Kyiv, Moscow, Beijing, Tokyo, London +more<br>\u2022 <span style="color:#4A90D9">AIT Taipei</span> \u2014 De facto US embassy to Taiwan<br>\u2022 <span style="color:#E8B339">Foreign Missions in DC</span> \u2014 Chinese, Russian, Iranian interests<br><br>Includes strategic context: staffing levels, intelligence significance, military coordination roles.`);
  }else if(q.includes('base')||q.includes('installation')){
    msg('sy',(BRIEFS.bases&&BRIEFS.bases())||'Military bases module loading...');
  }else if(q.includes('nuke')||q.includes('nuclear')){
    msg('sy',(BRIEFS.nuclear&&BRIEFS.nuclear())||'Nuclear sites module loading...');
  }else if(q.includes('squawk')||q.includes('emergency code')||q.includes('7700')||q.includes('7500')){
    msg('sy',(BRIEFS.squawk&&BRIEFS.squawk())||'Squawk monitoring module loading...');
  }else if(q.startsWith('ip ')||q==='my ip'||q==='myip'||q.includes('ip lookup')||q.includes('trace ip')||q.includes('geolocate ip')||q.includes('whois')){
    // IP Intelligence via ip2location.io
    const ipMatch=q.match(/(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})/);
    if(ipMatch){
      const targetIP=ipMatch[1];
      msg('sy',`<b>&#128270; IP INTEL — QUERYING</b><br>Target: <b>${esc(targetIP)}</b><br>Source: ip2location.io<br><br>Geolocating + proxy/VPN/TOR detection...`);
      IPIntel.lookupAndPlot(targetIP).then(d=>{
        if(d){
          const isP=d.is_proxy;const pType=d.proxy_type||'';
          msg('sy',`<b>&#127760; IP INTELLIGENCE REPORT</b><br><br><table style="width:100%;font-size:11px"><tr><td style="color:#7a8194;padding:2px 0">IP</td><td><b>${esc(d.ip)}</b></td></tr><tr><td style="color:#7a8194">LOCATION</td><td>${esc(d.city_name||d.city||'')}, ${esc(d.region_name||d.region||'')}, ${esc(d.country_name||d.country_code||'')}</td></tr><tr><td style="color:#7a8194">ISP</td><td>${esc(d.isp||d.as||'Unknown')}</td></tr><tr><td style="color:#7a8194">ASN</td><td>${esc(String(d.asn||d.as||''))}</td></tr><tr><td style="color:#7a8194">PROXY/VPN</td><td style="color:${isP?'#DA3633':'#52b788'};font-weight:700">${isP?'YES — '+esc(pType):'CLEAN'}</td></tr>${d.domain?'<tr><td style="color:#7a8194">DOMAIN</td><td>'+esc(d.domain)+'</td></tr>':''}${d.usage_type?'<tr><td style="color:#7a8194">USAGE</td><td>'+esc(d.usage_type)+'</td></tr>':''}</table><br><span style="color:#4a5068;font-size:9px">Marker plotted on globe. Source: ip2location.io</span>`);
        }else{msg('sy',`<span style="color:#c4504a">IP lookup failed for ${esc(targetIP)}. Check key/rate limit.</span>`)}
      });
    }else if(q==='my ip'||q==='myip'||q.includes('my ip')){
      msg('sy','<b>&#128270; DETECTING YOUR PUBLIC IP...</b>');
      IPIntel.getMyIP().then(d=>{
        if(d){
          msg('sy',`<b>&#127760; YOUR IP PROFILE</b><br><br><b>${esc(d.ip)}</b><br>${esc(d.city_name||d.city||'')}, ${esc(d.region_name||d.region||'')}, ${esc(d.country_name||d.country_code||'')}<br>ISP: ${esc(d.isp||d.as||'Unknown')}<br>Proxy: ${d.is_proxy?'<span style="color:#DA3633">YES — '+esc(d.proxy_type||'')+'</span>':'<span style="color:#52b788">NO</span>'}`);
          IPIntel.lookupAndPlot(d.ip);
        }else{msg('sy','<span style="color:#c4504a">Could not detect your IP.</span>')}
      });
    }else{
      msg('sy',`<b>&#128270; IP INTELLIGENCE</b><br><br>Usage:<br>\u2022 <b>ip 8.8.8.8</b> — Geolocate + proxy/VPN/TOR check<br>\u2022 <b>ip 203.0.113.1</b> — Any IPv4 address<br>\u2022 <b>my ip</b> — Show your public IP + location<br>\u2022 <b>ip clear</b> — Remove plotted IP markers<br><br>Powered by ip2location.io — detects proxy, VPN, TOR exit nodes, data centers, and web crawlers.`);
    }
  }else if(q==='ip clear'||q==='clear ip'){
    IPIntel.clearMarkers();
    msg('sy','IP markers cleared from globe.');
  }else if(q.includes('veg')||q.includes('vegetation')||q.includes('plant')||q.includes('terrain')||q.includes('canopy')||q.includes('ndvi')||q.includes('flora')||q.includes('jungle')||q.includes('forest')){
    if(!layers.vegetation){const el=document.querySelector('[data-layer="vegetation"]');if(el)togLy(el)}
    const cam=V?Cesium.Cartographic.fromCartesian(V.camera.positionWC):null;
    const clat=cam?Cesium.Math.toDegrees(cam.latitude):0;
    const clon=cam?Cesium.Math.toDegrees(cam.longitude):0;
    if(q.includes('scan')){
      VegIntel.scanPoint(clat,clon);
      msg('sy',`<b>&#127793; VEGETATION SCAN INITIATED</b><br><br>Scanning <b>${clat.toFixed(2)}°, ${clon.toFixed(2)}°</b> for terrain/vegetation classification...<br><br>Results appearing in VEG INTEL panel (top-right).`);
    }else{
      const hz=VegIntel.getHardinessZone(clat);
      const ndvi=VegIntel._syntheticNDVI(clat,clon);
      const terrain=VegIntel.classifyTerrain(ndvi,clat,0);
      msg('sy',`<b>&#127793; VEGETATION INTELLIGENCE</b><br><br><b>3 APIs Active:</b><br>\u2022 <b>Perenual</b> — Plant species database, hardiness zones, care data<br>\u2022 <b>Plant.id v3</b> — ML plant identification from photos, health assessment<br>\u2022 <b>iNaturalist</b> — Crowdsourced species observations (research-grade)<br><br><b>Current View (${clat.toFixed(1)}°, ${clon.toFixed(1)}°):</b><br>\u2022 Terrain: <b style="color:${terrain.color}">${terrain.type}</b><br>\u2022 NDVI: ${ndvi.toFixed(3)}<br>\u2022 Hardiness Zone: ${hz.zone} (${hz.label})<br>\u2022 Canopy: ${hz.canopy}<br><br><b>Usage:</b><br>\u2022 Toggle <b>Vegetation Intelligence</b> layer for grid overlay<br>\u2022 <b>Right-click</b> any point → Scan Vegetation for detailed analysis<br>\u2022 Type <b>veg scan</b> to scan current camera center<br>\u2022 Drag/drop a plant photo for Plant.id ML identification<br><br><b>TACTICAL VALUE:</b> Know if your AO is triple canopy jungle, open desert, or sparse rocky terrain before boots hit the ground.`);
    }
  }else{
    msg('sy',`No briefing found for "<b>${esc(q)}</b>".<br><br>Available: <b>iran</b>, <b>ukraine</b>, <b>china</b>, <b>force tracker</b>, <b>satellite</b>, <b>earthquake</b>, <b>fire</b>, <b>chokepoints</b>, <b>internet</b>, <b>cables</b>, <b>anomalies</b>, <b>export brief</b>, <b>history</b>, <b>health</b>, <b>status</b>, <b>bases</b>, <b>nuclear</b>, <b>squawk</b>, <b>debt</b>, <b>sanctions</b>, <b>alliances</b>, <b>oil/gas</b>, <b>power plants</b>, <b>embassy</b>, <b>vegetation</b>, <b>ip [addr]</b>, <b>help</b>`);
  }
}
